/// Simple localization service for Vietnamese and English.
class AppLocalizations {
  final String locale; // 'vi' or 'en'

  AppLocalizations(this.locale);

  String get(String key) =>
      (_strings[locale]?[key]) ?? (_strings['vi']?[key]) ?? key;

  static const Map<String, Map<String, String>> _strings = {
    'vi': {
      // App
      'app_name': 'Quản lý Cây',
      'app_subtitle': 'EarthRanger',
      'version': 'v1.0.0',
      'landing_title': 'V-RANGER',
      'landing_open_earthranger': 'MỞ\nEARTHRANGER',
      'landing_add_tree': 'THÊM CÂY',
      'landing_user_name': 'Nguyễn Minh Đức',
      'landing_user_role': 'Trưởng Đội Tuần Tra - Đội 01',
      'landing_user_status_on_duty': 'Đang trực',
      'landing_user_date': 'Thứ Sáu, 26 Th01 2024',
      'landing_function_work': 'Quản lý Công việc',
      'landing_function_incident': 'Quản lý sự cố',
      'landing_function_resource': 'Quản lý Tài nguyên Rừng',
      'landing_function_schedule': 'Lịch làm việc',
      'landing_function_reports': 'Thống kê báo cáo',
      'landing_function_patrol': 'Quản lý Tuần tra',

      // Home
      'home': 'Trang chủ',
      'nfc_hint': 'Nhập mã NFC hoặc Tree ID',
      'nfc_empty_error': 'Vui lòng nhập mã NFC.',
      'nfc_scan_prompt': 'Vui lòng để điện thoại gần thẻ NFC',
      'nfc_unavailable_error': 'NFC lỗi: không khả dụng hoặc đang tắt.',
      'nfc_uid_read_error': 'Không thể đọc mã UID từ thẻ NFC.',
      'nfc_ios_unavailable_temp': 'Chức năng NFC tạm thời không có trên iOS.',
      'search': 'Tìm kiếm',
      'search_failed':
          'Tìm kiếm thất bại. Vui lòng kiểm tra kết nối và thử lại.',
      'link_tree_action': 'Liên kết cây',
      'id_label': 'ID',
      'not_available': 'N/A',
      'maps': 'Bản đồ',
      'alerts': 'Cảnh báo',
      'notifications': 'Thông báo',
      'account': 'Tài khoản',
      'placeholder_coming_soon': 'Màn hình chức năng đang được phát triển.',
      'work_checkin_title': 'Điểm danh khi mở ứng dụng',
      'work_checkin_syncing': 'Đang đồng bộ điểm danh...',
      'work_checkin_status_created': 'Đã ghi nhận điểm danh hôm nay',
      'work_checkin_status_exists': 'Hôm nay đã điểm danh trước đó',
      'work_checkin_status_pending': 'Đã lưu tạm, chờ đồng bộ khi có mạng',
      'work_checkin_status_unknown': 'Chưa có trạng thái điểm danh',
      'work_checkin_day_pending': 'Ngày điểm danh: chưa có dữ liệu',
      'work_checkin_day_prefix': 'Ngày điểm danh: ',
      'work_checkin_error_prefix': 'Lỗi điểm danh: ',
      'work_sync_status_title': 'Trạng thái đồng bộ',
      'work_sync_status_empty': 'Chưa có bản ghi đồng bộ cục bộ.',
      'work_sync_status_pending': 'Đang chờ',
      'work_sync_status_synced': 'Đã đồng bộ',
      'work_sync_status_failed': 'Thất bại',
      'work_sync_status_count_pending': 'Chờ',
      'work_sync_status_count_failed': 'Lỗi',
      'work_sync_status_count_synced': 'Đồng bộ',
      'work_sync_status_updated_prefix': 'Cập nhật: ',
      'work_sync_status_retry_at_prefix': 'Thử lại lúc: ',
      'work_sync_status_error_prefix': 'Lỗi: ',
      'work_sync_status_retry_item': 'Thử lại mục này',
      'work_sync_status_retry_all': 'Thử lại tất cả mục lỗi',
      'work_sync_status_retrying': 'Đang thử lại mục lỗi...',
        'work_calendar_role_label': 'Vai trò',
        'work_calendar_role_leader': 'Trưởng nhóm',
        'work_calendar_role_ranger': 'Kiểm lâm',
        'work_calendar_scope_team': 'Phạm vi: toàn đội',
        'work_calendar_scope_self': 'Phạm vi: cá nhân',
        'work_calendar_filter_label': 'Lọc kiểm lâm',
        'work_calendar_filter_all': 'Tất cả kiểm lâm',
        'work_calendar_loading': 'Đang tải dữ liệu lịch công việc...',
        'work_calendar_empty': 'Không có dữ liệu lịch cho phạm vi và tháng đã chọn.',
        'work_calendar_error': 'Không thể tải dữ liệu lịch công việc.',
        'work_calendar_retry': 'Tải lại',
        'work_calendar_last_sync_prefix': 'Đồng bộ gần nhất: ',
        'work_calendar_last_sync_unknown': 'chưa có dữ liệu',
        'work_calendar_stale_banner':
          'Dữ liệu lịch công việc có thể đã cũ. Vui lòng làm mới khi có mạng.',
        'work_calendar_offline_banner':
          'Đang hiển thị dữ liệu đã lưu do kết nối mạng không ổn định.',
        'work_calendar_refresh_error_prefix': 'Lỗi làm mới: ',
        'work_calendar_day_no_data': 'Ngày đã chọn chưa có dữ liệu công việc.',
        'work_calendar_day_all_checked':
          'Ngày đã chọn: tất cả bản ghi đã điểm danh.',
        'work_calendar_day_none_checked':
          'Ngày đã chọn: chưa có bản ghi điểm danh.',
        'work_calendar_day_partial_prefix': 'Ngày đã chọn: ',
        'work_calendar_day_partial_suffix':
          ' bản ghi đã điểm danh (một phần).',
          'incident_scope_label': 'Phạm vi sự cố',
          'incident_role_leader': 'Trưởng nhóm',
          'incident_role_ranger': 'Kiểm lâm',
          'incident_scope_team': 'Hiển thị toàn đội',
          'incident_scope_self': 'Hiển thị cá nhân',
          'incident_last_sync_prefix': 'Đồng bộ gần nhất: ',
          'incident_last_sync_unknown': 'chưa có dữ liệu',
          'incident_loading': 'Đang tải danh sách sự cố...',
          'incident_empty': 'Không có sự cố nào trong khoảng thời gian đã chọn.',
          'incident_error': 'Không thể tải danh sách sự cố.',
          'incident_retry': 'Thử tải lại',
          'incident_stale_banner':
            'Dữ liệu có thể đã cũ. Vui lòng kéo xuống hoặc nhấn làm mới.',
          'incident_offline_banner':
            'Đang hiển thị dữ liệu đã lưu do thiết bị đang offline hoặc mạng lỗi.',
          'incident_cached_banner':
            'Đang hiển thị dữ liệu cache trong khi làm mới nền.',
          'incident_leakage_filtered_banner':
            'Đã lọc dữ liệu sự cố ngoài phạm vi hiển thị của bạn để bảo toàn quyền truy cập.',
          'incident_refresh_error_prefix': 'Lỗi làm mới: ',
          'incident_refresh_retry_hint': 'Nhấn làm mới để thử lại.',
          'incident_error_timeout': 'Hết thời gian chờ khi tải dữ liệu sự cố.',
          'incident_error_network': 'Mạng không khả dụng.',
          'incident_error_unexpected': 'Đã xảy ra lỗi không mong muốn.',
          'incident_unknown_title': 'Sự cố chưa có tiêu đề',
          'incident_unknown_time': 'Không rõ thời gian',
          'incident_empty_stale':
            'Không có sự cố trong bản dữ liệu cũ. Vui lòng làm mới khi có mạng.',
          'incident_unknown_severity': 'Không rõ mức độ',
          'incident_unknown_status': 'Không rõ trạng thái',
          'incident_status_prefix': 'Trạng thái: ',
          'incident_time_prefix': 'Thời điểm: ',
          'incident_ranger_prefix': 'Kiểm lâm: ',
            'schedule_scope_label': 'Phạm vi lịch',
            'schedule_role_leader': 'Trưởng nhóm',
            'schedule_role_ranger': 'Kiểm lâm',
            'schedule_scope_team': 'Hiển thị toàn đội',
            'schedule_scope_self': 'Hiển thị cá nhân',
            'schedule_filter_label': 'Lọc kiểm lâm',
            'schedule_filter_all': 'Tất cả kiểm lâm',
            'schedule_filter_all_staff': 'Tất cả trưởng nhóm/kiểm lâm',
            'schedule_loading': 'Đang tải lịch làm việc...',
            'schedule_empty': 'Không có lịch làm việc trong tháng đã chọn.',
            'schedule_error': 'Không thể tải lịch làm việc.',
            'schedule_retry': 'Thử tải lại',
            'schedule_last_sync_prefix': 'Đồng bộ gần nhất: ',
            'schedule_last_sync_unknown': 'chưa có dữ liệu',
            'schedule_stale_banner':
              'Dữ liệu lịch có thể đã cũ. Vui lòng làm mới khi có mạng.',
            'schedule_offline_banner':
              'Đang hiển thị dữ liệu đã lưu do kết nối mạng không ổn định.',
            'schedule_refresh_error_prefix': 'Lỗi làm mới: ',
            'schedule_create': 'Tạo lịch',
            'schedule_edit': 'Chỉnh sửa lịch',
            'schedule_delete': 'Xoá lịch',
            'schedule_delete_confirm_title': 'Xoá lịch làm việc',
            'schedule_delete_confirm_message':
              'Bạn có chắc muốn xoá lịch làm việc này không?',
            'schedule_delete_confirm_action': 'Xoá',
            'schedule_delete_success': 'Đã xoá lịch làm việc.',
            'schedule_delete_error': 'Không thể xoá lịch làm việc.',
            'schedule_delete_error_prefix': 'Lỗi xoá lịch: ',
            'schedule_form_title_create': 'Tạo lịch làm việc',
            'schedule_form_title_edit': 'Cập nhật lịch làm việc',
            'schedule_form_ranger_label': 'Người được phân công',
            'schedule_form_date_label': 'Ngày làm việc',
            'schedule_form_note_label': 'Ghi chú',
            'schedule_form_note_hint': 'Nhập ghi chú phân công (tuỳ chọn)',
            'schedule_form_save': 'Lưu',
            'schedule_form_saving': 'Đang lưu...',
            'schedule_form_cancel': 'Huỷ',
            'schedule_validation_ranger_required': 'Vui lòng chọn người được phân công.',
            'schedule_validation_work_date_required': 'Vui lòng chọn ngày làm việc.',
            'schedule_submit_error_prefix': 'Lỗi lưu lịch: ',
            'schedule_date_prefix': 'Ngày: ',
            'schedule_ranger_prefix': 'Kiểm lâm: ',
            'schedule_note_empty': 'Không có ghi chú.',
            'schedule_updated_by_prefix': 'Cập nhật bởi: ',
            'schedule_updated_at_prefix': 'Cập nhật lúc: ',
            'schedule_updated_by_unknown': 'không rõ',
            'schedule_updated_at_unknown': 'không rõ',

      // Admin login dialog
      'login_status_logged_in': 'Trạng thái: Đã đăng nhập Admin',
      'login_status_logged_out': 'Trạng thái: Chưa đăng nhập',
      'sign_in_title': 'Đăng nhập',
      'sign_in_subtitle': 'Dùng tài khoản EarthRanger để tiếp tục',
      'sign_in_action': 'Đăng nhập',
      'remember_me': 'Ghi nhớ đăng nhập',
      'restoring_session': 'Đang khôi phục phiên đăng nhập...',
      'login': 'Đăng nhập',
      'logout': 'Đăng xuất',
      'cancel': 'Hủy',
      'username_hint': 'Tên đăng nhập',
      'password_hint': 'Mật khẩu',
      'username_empty_error': 'Vui lòng nhập tên đăng nhập.',
      'password_empty_error': 'Vui lòng nhập mật khẩu.',
      'login_success': 'Đăng nhập Admin thành công!',
      'login_failed': 'Sai tên đăng nhập hoặc mật khẩu!',
      'login_empty_error': 'Vui lòng nhập tên đăng nhập và mật khẩu.',
      'invalid_credentials': 'Tên đăng nhập hoặc mật khẩu không đúng.',
      'network_error_try_again': 'Không thể kết nối. Vui lòng thử lại.',
      'session_expired_relogin': 'Phiên đã hết hạn. Vui lòng đăng nhập lại.',
      'show_password': 'Hiện mật khẩu',
      'hide_password': 'Ẩn mật khẩu',
      'login_not_configured': 'Đăng nhập Admin chưa được cấu hình.',
      'logged_out': 'Đã đăng xuất khỏi Admin',
      'signed_out': 'Bạn đã đăng xuất.',
      'admin_login': 'Đăng nhập Admin',

      // Tree detail
      'tree_info': 'Thông tin Cây',
      'species': 'Loài',
      'age': 'Tuổi',
      'height': 'Chiều cao',
      'diameter': 'Đường kính',
      'canopy': 'Tán lá',
      'condition': 'Tình trạng',
      'latitude': 'Vĩ độ',
      'longitude': 'Kinh độ',
      'created_at': 'Ngày tạo',
      'creator': 'Người tạo',
      'last_reported': 'Cập nhật cuối',
      'updater': 'Người cập nhật',
      'event_status': 'Trạng thái sự kiện',
      'sn': 'SN',
      'synced_at': 'Đồng bộ lúc',
      'nfc_id': 'NFC ID',
      'not_found': 'Không tìm thấy cây',
      'not_found_detail': 'Không tìm thấy dữ liệu cho mã NFC này.',
      'go_back': 'Quay lại',
      'no_images': 'Không có hình ảnh',
      'no_nfc': 'Không có mã NFC được cung cấp.',
      'fetch_failed': 'Lấy dữ liệu cây thất bại.',
      'no_edit_permission': 'Bạn không có quyền chỉnh sửa.',
      'no_data_to_edit': 'Không có dữ liệu để chỉnh sửa.',

      // Edit dialog
      'edit_tree': 'Chỉnh sửa thông tin cây',
      'tree_id_label': 'Tree ID',
      'tree_id_required': 'Vui lòng nhập Tree ID',
      'save': 'Lưu',
      'update_success': 'Cập nhật thông tin thành công!',
      'update_failed': 'Cập nhật thất bại',
      'condition_good': 'Tốt',
      'condition_average': 'Trung bình',
      'condition_bad': 'Xấu',

      // Section headers
      'stats': 'Thông số',
      'history': 'Lịch sử',
      'technical': 'Thông tin kỹ thuật',

      // Settings
      'settings': 'Cài đặt',
      'language': 'Ngôn ngữ',
      'vietnamese': 'Tiếng Việt',
      'english': 'English',
      'theme': 'Giao diện',
      'light_mode': 'Sáng',
      'dark_mode': 'Tối',
      'system_mode': 'Theo hệ thống',
      'appearance': 'Hiển thị',
      'general': 'Chung',

      // Link tree
      'link_nfc': 'Liên kết NFC',
      'link_nfc_title': 'Chọn cây để liên kết',
      'search_tree_hint': 'Tìm kiếm theo ID hoặc loài',
      'unlinked_trees': 'Cây chưa liên kết',
      'linked_trees': 'Cây đã liên kết',
      'has_nfc': 'Đã có NFC',
      'no_nfc_tag': 'Chưa có NFC',
      'replace_nfc_title': 'Thay thế NFC',
      'replace_nfc_message':
          'Cây {id} đã có NFC: {nfc}. Bạn có muốn thay thế không?',
      'confirm': 'Xác nhận',
      'link_success': 'Liên kết NFC thành công!',
      'link_failed': 'Liên kết thất bại',
      'no_trees_found': 'Không tìm thấy cây nào',
      'retry': 'Thử lại',
    },
    'en': {
      // App
      'app_name': 'Tree Manager',
      'app_subtitle': 'EarthRanger',
      'version': 'v1.0.0',
      'landing_title': 'V-RANGER',
      'landing_open_earthranger': 'OPEN\nEARTHRANGER',
      'landing_add_tree': 'ADD TREE',
      'landing_user_name': 'Nguyen Minh Duc',
      'landing_user_role': 'Patrol Team Leader - Team 01',
      'landing_user_status_on_duty': 'On Duty',
      'landing_user_date': 'Friday, Jan 26 2024',
      'landing_function_work': 'Work Management',
      'landing_function_incident': 'Incident Management',
      'landing_function_resource': 'Forest Resource Management',
      'landing_function_schedule': 'Work Schedule',
      'landing_function_reports': 'Report Statistics',
      'landing_function_patrol': 'Patrol Management',

      // Home
      'home': 'Home',
      'nfc_hint': 'Enter NFC code or Tree ID',
      'nfc_empty_error': 'Please enter an NFC code.',
      'nfc_scan_prompt': 'Please hold your phone near the NFC tag',
      'nfc_unavailable_error': 'NFC error: unavailable or disabled.',
      'nfc_uid_read_error': 'Could not read NFC UID from the tag.',
      'nfc_ios_unavailable_temp': 'NFC is temporarily unavailable on iOS.',
      'search': 'Search',
      'search_failed':
          'Search failed. Please check your connection and try again.',
      'link_tree_action': 'Link tree',
      'id_label': 'ID',
      'not_available': 'N/A',
      'maps': 'Maps',
      'alerts': 'Alerts',
      'notifications': 'Notifications',
      'account': 'Account',
      'placeholder_coming_soon': 'This feature screen is coming soon.',
      'work_checkin_title': 'App-open check-in',
      'work_checkin_syncing': 'Syncing check-in...',
      'work_checkin_status_created': 'Check-in recorded for today',
      'work_checkin_status_exists': 'Check-in already exists for today',
      'work_checkin_status_pending': 'Queued offline, waiting for replay',
      'work_checkin_status_unknown': 'No check-in status yet',
      'work_checkin_day_pending': 'Check-in day: no data yet',
      'work_checkin_day_prefix': 'Check-in day: ',
      'work_checkin_error_prefix': 'Check-in error: ',
      'work_sync_status_title': 'Sync status',
      'work_sync_status_empty': 'No local sync records yet.',
      'work_sync_status_pending': 'Pending',
      'work_sync_status_synced': 'Synced',
      'work_sync_status_failed': 'Failed',
      'work_sync_status_count_pending': 'Pending',
      'work_sync_status_count_failed': 'Failed',
      'work_sync_status_count_synced': 'Synced',
      'work_sync_status_updated_prefix': 'Updated: ',
      'work_sync_status_retry_at_prefix': 'Retry at: ',
      'work_sync_status_error_prefix': 'Error: ',
      'work_sync_status_retry_item': 'Retry this item',
      'work_sync_status_retry_all': 'Retry all failed items',
      'work_sync_status_retrying': 'Retrying failed items...',
        'work_calendar_role_label': 'Role',
        'work_calendar_role_leader': 'Leader',
        'work_calendar_role_ranger': 'Ranger',
        'work_calendar_scope_team': 'Scope: team view',
        'work_calendar_scope_self': 'Scope: self view',
        'work_calendar_filter_label': 'Ranger filter',
        'work_calendar_filter_all': 'All rangers',
        'work_calendar_loading': 'Loading work calendar data...',
        'work_calendar_empty': 'No calendar data for the selected scope and month.',
        'work_calendar_error': 'Unable to load Work Management data.',
        'work_calendar_retry': 'Retry',
        'work_calendar_last_sync_prefix': 'Last sync: ',
        'work_calendar_last_sync_unknown': 'no sync data',
        'work_calendar_stale_banner':
          'Work calendar data may be stale. Refresh when network is available.',
        'work_calendar_offline_banner':
          'Showing cached data because the network is currently unavailable.',
        'work_calendar_refresh_error_prefix': 'Refresh error: ',
        'work_calendar_day_no_data': 'No work data for the selected day.',
        'work_calendar_day_all_checked':
          'Selected day: all records have confirmed check-in.',
        'work_calendar_day_none_checked':
          'Selected day: no records have check-in yet.',
        'work_calendar_day_partial_prefix': 'Selected day: ',
        'work_calendar_day_partial_suffix':
          ' records have check-in (partial coverage).',
          'incident_scope_label': 'Incident scope',
          'incident_role_leader': 'Leader',
          'incident_role_ranger': 'Ranger',
          'incident_scope_team': 'Team-wide view',
          'incident_scope_self': 'Self-only view',
          'incident_last_sync_prefix': 'Last sync: ',
          'incident_last_sync_unknown': 'no sync data',
          'incident_loading': 'Loading incidents...',
          'incident_empty': 'No incidents found for the selected period.',
          'incident_error': 'Unable to load incidents.',
          'incident_retry': 'Retry',
          'incident_stale_banner':
            'Data may be stale. Pull to refresh or tap refresh.',
          'incident_offline_banner':
            'Showing cached data because the device is offline or network refresh failed.',
          'incident_cached_banner':
            'Showing cached data while a background refresh is in progress.',
          'incident_leakage_filtered_banner':
            'Out-of-scope incident records were filtered to preserve access boundaries.',
          'incident_refresh_error_prefix': 'Refresh error: ',
          'incident_refresh_retry_hint': 'Tap refresh to retry.',
          'incident_error_timeout': 'Request timed out while loading incidents.',
          'incident_error_network': 'Network unavailable.',
          'incident_error_unexpected': 'An unexpected error occurred.',
          'incident_unknown_title': 'Untitled incident',
          'incident_unknown_time': 'Unknown time',
          'incident_empty_stale':
            'No incidents found in stale data. Refresh when network is available.',
          'incident_unknown_severity': 'Unknown severity',
          'incident_unknown_status': 'Unknown status',
          'incident_status_prefix': 'Status: ',
          'incident_time_prefix': 'Time: ',
          'incident_ranger_prefix': 'Ranger: ',
            'schedule_scope_label': 'Schedule scope',
            'schedule_role_leader': 'Leader',
            'schedule_role_ranger': 'Ranger',
            'schedule_scope_team': 'Team-wide view',
            'schedule_scope_self': 'Self-only view',
            'schedule_filter_label': 'Ranger filter',
            'schedule_filter_all': 'All rangers',
            'schedule_filter_all_staff': 'All leaders/rangers',
            'schedule_loading': 'Loading schedules...',
            'schedule_empty': 'No schedules found for the selected month.',
            'schedule_error': 'Unable to load schedules.',
            'schedule_retry': 'Retry',
            'schedule_last_sync_prefix': 'Last sync: ',
            'schedule_last_sync_unknown': 'no sync data',
            'schedule_stale_banner':
              'Schedule data may be stale. Refresh when network is available.',
            'schedule_offline_banner':
              'Showing cached data because the network is currently unavailable.',
            'schedule_refresh_error_prefix': 'Refresh error: ',
            'schedule_create': 'Create schedule',
            'schedule_edit': 'Edit schedule',
            'schedule_delete': 'Delete schedule',
            'schedule_delete_confirm_title': 'Delete schedule',
            'schedule_delete_confirm_message':
              'Are you sure you want to delete this work schedule?',
            'schedule_delete_confirm_action': 'Delete',
            'schedule_delete_success': 'Schedule deleted.',
            'schedule_delete_error': 'Unable to delete schedule.',
            'schedule_delete_error_prefix': 'Schedule delete error: ',
            'schedule_form_title_create': 'Create schedule',
            'schedule_form_title_edit': 'Update schedule',
            'schedule_form_ranger_label': 'Assignee',
            'schedule_form_date_label': 'Work date',
            'schedule_form_note_label': 'Note',
            'schedule_form_note_hint': 'Enter assignment note (optional)',
            'schedule_form_save': 'Save',
            'schedule_form_saving': 'Saving...',
            'schedule_form_cancel': 'Cancel',
            'schedule_validation_ranger_required': 'Please select an assignee.',
            'schedule_validation_work_date_required': 'Please select a work date.',
            'schedule_submit_error_prefix': 'Schedule save error: ',
            'schedule_date_prefix': 'Date: ',
            'schedule_ranger_prefix': 'Ranger: ',
            'schedule_note_empty': 'No note provided.',
            'schedule_updated_by_prefix': 'Updated by: ',
            'schedule_updated_at_prefix': 'Updated at: ',
            'schedule_updated_by_unknown': 'unknown',
            'schedule_updated_at_unknown': 'unknown',

      // Admin login dialog
      'login_status_logged_in': 'Status: Admin logged in',
      'login_status_logged_out': 'Status: Not logged in',
      'sign_in_title': 'Sign in',
      'sign_in_subtitle': 'Use your EarthRanger account to continue',
      'sign_in_action': 'Sign in',
      'remember_me': 'Remember me',
      'restoring_session': 'Restoring your session...',
      'login': 'Login',
      'logout': 'Logout',
      'cancel': 'Cancel',
      'username_hint': 'Username',
      'password_hint': 'Password',
      'username_empty_error': 'Please enter username.',
      'password_empty_error': 'Please enter password.',
      'login_success': 'Admin login successful!',
      'login_failed': 'Wrong username or password!',
      'login_empty_error': 'Please enter username and password.',
      'invalid_credentials': 'Username or password is incorrect.',
      'network_error_try_again': 'Cannot connect. Please try again.',
      'session_expired_relogin': 'Session expired. Please sign in again.',
      'show_password': 'Show password',
      'hide_password': 'Hide password',
      'login_not_configured': 'Admin login is not configured.',
      'logged_out': 'Logged out from Admin',
      'signed_out': 'You have been signed out.',
      'admin_login': 'Admin Login',

      // Tree detail
      'tree_info': 'Tree Info',
      'species': 'Species',
      'age': 'Age',
      'height': 'Height',
      'diameter': 'Diameter',
      'canopy': 'Canopy',
      'condition': 'Condition',
      'latitude': 'Latitude',
      'longitude': 'Longitude',
      'created_at': 'Created',
      'creator': 'Creator',
      'last_reported': 'Last reported',
      'updater': 'Updater',
      'event_status': 'Event status',
      'sn': 'SN',
      'synced_at': 'Synced at',
      'nfc_id': 'NFC ID',
      'not_found': 'Tree not found',
      'not_found_detail': 'No data found for this NFC code.',
      'go_back': 'Go back',
      'no_images': 'No images',
      'no_nfc': 'No NFC code provided.',
      'fetch_failed': 'Failed to fetch tree data.',
      'no_edit_permission': 'You do not have edit permission.',
      'no_data_to_edit': 'No data to edit.',

      // Edit dialog
      'edit_tree': 'Edit tree info',
      'tree_id_label': 'Tree ID',
      'tree_id_required': 'Please enter Tree ID',
      'save': 'Save',
      'update_success': 'Update successful!',
      'update_failed': 'Update failed',
      'condition_good': 'Good',
      'condition_average': 'Average',
      'condition_bad': 'Bad',

      // Section headers
      'stats': 'Statistics',
      'history': 'History',
      'technical': 'Technical Info',

      // Settings
      'settings': 'Settings',
      'language': 'Language',
      'vietnamese': 'Tiếng Việt',
      'english': 'English',
      'theme': 'Theme',
      'light_mode': 'Light',
      'dark_mode': 'Dark',
      'system_mode': 'System',
      'appearance': 'Appearance',
      'general': 'General',

      // Link tree
      'link_nfc': 'Link NFC',
      'link_nfc_title': 'Select tree to link',
      'search_tree_hint': 'Search by ID or species',
      'unlinked_trees': 'Unlinked trees',
      'linked_trees': 'Linked trees',
      'has_nfc': 'Has NFC',
      'no_nfc_tag': 'No NFC',
      'replace_nfc_title': 'Replace NFC',
      'replace_nfc_message':
          'Tree {id} already has NFC: {nfc}. Do you want to replace it?',
      'confirm': 'Confirm',
      'link_success': 'NFC linked successfully!',
      'link_failed': 'Link failed',
      'no_trees_found': 'No trees found',
      'retry': 'Retry',
    },
  };
}
