/// Simple localization service for Vietnamese and English.
class AppLocalizations {
  final String locale; // 'vi' or 'en'

  AppLocalizations(this.locale);

  String get(String key) =>
      (_strings[locale]?[key]) ?? (_strings['vi']?[key]) ?? key;

  static const Map<String, Map<String, String>> _strings = {
    'vi': {
      // App
      'app_name': 'Quản lý Cây',
      'app_subtitle': 'EarthRanger',
      'version': 'v1.0.0',
      'landing_title': 'V-RANGER',
      'landing_open_earthranger': 'MỞ\nEARTHRANGER',
      'landing_add_tree': 'THÊM CÂY',
      'landing_user_name': 'Nguyễn Minh Đức',
      'landing_user_role': 'Trưởng Đội Tuần Tra - Đội 01',
      'landing_user_status_on_duty': 'Đang trực',
      'landing_user_date': 'Thứ Sáu, 26 Th01 2024',
      'landing_function_work': 'Quản lý Công việc',
      'landing_function_incident': 'Quản lý sự cố',
      'landing_function_resource': 'Quản lý Tài nguyên Rừng',
      'landing_function_schedule': 'Lịch làm việc',
      'landing_function_reports': 'Thống kê báo cáo',
      'landing_function_patrol': 'Quản lý Tuần tra',

      // Home
      'home': 'Trang chủ',
      'nfc_hint': 'Nhập mã NFC hoặc Tree ID',
      'nfc_empty_error': 'Vui lòng nhập mã NFC.',
      'nfc_scan_prompt': 'Vui lòng để điện thoại gần thẻ NFC',
      'nfc_unavailable_error': 'NFC lỗi: không khả dụng hoặc đang tắt.',
      'nfc_uid_read_error': 'Không thể đọc mã UID từ thẻ NFC.',
      'nfc_ios_unavailable_temp': 'Chức năng NFC tạm thời không có trên iOS.',
      'search': 'Tìm kiếm',
      'search_failed':
          'Tìm kiếm thất bại. Vui lòng kiểm tra kết nối và thử lại.',
      'link_tree_action': 'Liên kết cây',
      'id_label': 'ID',
      'not_available': 'N/A',
      'maps': 'Bản đồ',
      'alerts': 'Cảnh báo',
      'notifications': 'Thông báo',
      'account': 'Tài khoản',
      'placeholder_coming_soon': 'Màn hình chức năng đang được phát triển.',

      // Admin login dialog
      'login_status_logged_in': 'Trạng thái: Đã đăng nhập Admin',
      'login_status_logged_out': 'Trạng thái: Chưa đăng nhập',
      'login': 'Đăng nhập',
      'logout': 'Đăng xuất',
      'cancel': 'Hủy',
      'username_hint': 'Tên đăng nhập',
      'password_hint': 'Mật khẩu',
      'username_empty_error': 'Vui lòng nhập tên đăng nhập.',
      'password_empty_error': 'Vui lòng nhập mật khẩu.',
      'login_success': 'Đăng nhập Admin thành công!',
      'login_failed': 'Sai tên đăng nhập hoặc mật khẩu!',
      'login_empty_error': 'Vui lòng nhập tên đăng nhập và mật khẩu.',
      'logged_out': 'Đã đăng xuất khỏi Admin',
      'admin_login': 'Đăng nhập Admin',

      // Tree detail
      'tree_info': 'Thông tin Cây',
      'species': 'Loài',
      'age': 'Tuổi',
      'height': 'Chiều cao',
      'diameter': 'Đường kính',
      'canopy': 'Tán lá',
      'condition': 'Tình trạng',
      'latitude': 'Vĩ độ',
      'longitude': 'Kinh độ',
      'created_at': 'Ngày tạo',
      'creator': 'Người tạo',
      'last_reported': 'Cập nhật cuối',
      'updater': 'Người cập nhật',
      'event_status': 'Trạng thái sự kiện',
      'sn': 'SN',
      'synced_at': 'Đồng bộ lúc',
      'nfc_id': 'NFC ID',
      'not_found': 'Không tìm thấy cây',
      'not_found_detail': 'Không tìm thấy dữ liệu cho mã NFC này.',
      'go_back': 'Quay lại',
      'no_images': 'Không có hình ảnh',
      'no_nfc': 'Không có mã NFC được cung cấp.',
      'fetch_failed': 'Lấy dữ liệu cây thất bại.',
      'no_edit_permission': 'Bạn không có quyền chỉnh sửa.',
      'no_data_to_edit': 'Không có dữ liệu để chỉnh sửa.',

      // Edit dialog
      'edit_tree': 'Chỉnh sửa thông tin cây',
      'tree_id_label': 'Tree ID',
      'tree_id_required': 'Vui lòng nhập Tree ID',
      'save': 'Lưu',
      'update_success': 'Cập nhật thông tin thành công!',
      'update_failed': 'Cập nhật thất bại',
      'condition_good': 'Tốt',
      'condition_average': 'Trung bình',
      'condition_bad': 'Xấu',

      // Section headers
      'stats': 'Thông số',
      'history': 'Lịch sử',
      'technical': 'Thông tin kỹ thuật',

      // Settings
      'settings': 'Cài đặt',
      'language': 'Ngôn ngữ',
      'vietnamese': 'Tiếng Việt',
      'english': 'English',
      'theme': 'Giao diện',
      'light_mode': 'Sáng',
      'dark_mode': 'Tối',
      'system_mode': 'Theo hệ thống',
      'appearance': 'Hiển thị',
      'general': 'Chung',

      // Link tree
      'link_nfc': 'Liên kết NFC',
      'link_nfc_title': 'Chọn cây để liên kết',
      'search_tree_hint': 'Tìm kiếm theo ID hoặc loài',
      'unlinked_trees': 'Cây chưa liên kết',
      'linked_trees': 'Cây đã liên kết',
      'has_nfc': 'Đã có NFC',
      'no_nfc_tag': 'Chưa có NFC',
      'replace_nfc_title': 'Thay thế NFC',
      'replace_nfc_message':
          'Cây {id} đã có NFC: {nfc}. Bạn có muốn thay thế không?',
      'confirm': 'Xác nhận',
      'link_success': 'Liên kết NFC thành công!',
      'link_failed': 'Liên kết thất bại',
      'no_trees_found': 'Không tìm thấy cây nào',
      'retry': 'Thử lại',
    },
    'en': {
      // App
      'app_name': 'Tree Manager',
      'app_subtitle': 'EarthRanger',
      'version': 'v1.0.0',
      'landing_title': 'V-RANGER',
      'landing_open_earthranger': 'OPEN\nEARTHRANGER',
      'landing_add_tree': 'ADD TREE',
      'landing_user_name': 'Nguyen Minh Duc',
      'landing_user_role': 'Patrol Team Leader - Team 01',
      'landing_user_status_on_duty': 'On Duty',
      'landing_user_date': 'Friday, Jan 26 2024',
      'landing_function_work': 'Work Management',
      'landing_function_incident': 'Incident Management',
      'landing_function_resource': 'Forest Resource Management',
      'landing_function_schedule': 'Work Schedule',
      'landing_function_reports': 'Report Statistics',
      'landing_function_patrol': 'Patrol Management',

      // Home
      'home': 'Home',
      'nfc_hint': 'Enter NFC code or Tree ID',
      'nfc_empty_error': 'Please enter an NFC code.',
      'nfc_scan_prompt': 'Please hold your phone near the NFC tag',
      'nfc_unavailable_error': 'NFC error: unavailable or disabled.',
      'nfc_uid_read_error': 'Could not read NFC UID from the tag.',
      'nfc_ios_unavailable_temp': 'NFC is temporarily unavailable on iOS.',
      'search': 'Search',
      'search_failed':
          'Search failed. Please check your connection and try again.',
      'link_tree_action': 'Link tree',
      'id_label': 'ID',
      'not_available': 'N/A',
      'maps': 'Maps',
      'alerts': 'Alerts',
      'notifications': 'Notifications',
      'account': 'Account',
      'placeholder_coming_soon': 'This feature screen is coming soon.',

      // Admin login dialog
      'login_status_logged_in': 'Status: Admin logged in',
      'login_status_logged_out': 'Status: Not logged in',
      'login': 'Login',
      'logout': 'Logout',
      'cancel': 'Cancel',
      'username_hint': 'Username',
      'password_hint': 'Password',
      'username_empty_error': 'Please enter username.',
      'password_empty_error': 'Please enter password.',
      'login_success': 'Admin login successful!',
      'login_failed': 'Wrong username or password!',
      'login_empty_error': 'Please enter username and password.',
      'logged_out': 'Logged out from Admin',
      'admin_login': 'Admin Login',

      // Tree detail
      'tree_info': 'Tree Info',
      'species': 'Species',
      'age': 'Age',
      'height': 'Height',
      'diameter': 'Diameter',
      'canopy': 'Canopy',
      'condition': 'Condition',
      'latitude': 'Latitude',
      'longitude': 'Longitude',
      'created_at': 'Created',
      'creator': 'Creator',
      'last_reported': 'Last reported',
      'updater': 'Updater',
      'event_status': 'Event status',
      'sn': 'SN',
      'synced_at': 'Synced at',
      'nfc_id': 'NFC ID',
      'not_found': 'Tree not found',
      'not_found_detail': 'No data found for this NFC code.',
      'go_back': 'Go back',
      'no_images': 'No images',
      'no_nfc': 'No NFC code provided.',
      'fetch_failed': 'Failed to fetch tree data.',
      'no_edit_permission': 'You do not have edit permission.',
      'no_data_to_edit': 'No data to edit.',

      // Edit dialog
      'edit_tree': 'Edit tree info',
      'tree_id_label': 'Tree ID',
      'tree_id_required': 'Please enter Tree ID',
      'save': 'Save',
      'update_success': 'Update successful!',
      'update_failed': 'Update failed',
      'condition_good': 'Good',
      'condition_average': 'Average',
      'condition_bad': 'Bad',

      // Section headers
      'stats': 'Statistics',
      'history': 'History',
      'technical': 'Technical Info',

      // Settings
      'settings': 'Settings',
      'language': 'Language',
      'vietnamese': 'Tiếng Việt',
      'english': 'English',
      'theme': 'Theme',
      'light_mode': 'Light',
      'dark_mode': 'Dark',
      'system_mode': 'System',
      'appearance': 'Appearance',
      'general': 'General',

      // Link tree
      'link_nfc': 'Link NFC',
      'link_nfc_title': 'Select tree to link',
      'search_tree_hint': 'Search by ID or species',
      'unlinked_trees': 'Unlinked trees',
      'linked_trees': 'Linked trees',
      'has_nfc': 'Has NFC',
      'no_nfc_tag': 'No NFC',
      'replace_nfc_title': 'Replace NFC',
      'replace_nfc_message':
          'Tree {id} already has NFC: {nfc}. Do you want to replace it?',
      'confirm': 'Confirm',
      'link_success': 'NFC linked successfully!',
      'link_failed': 'Link failed',
      'no_trees_found': 'No trees found',
      'retry': 'Retry',
    },
  };
}
