/// Simple localization service for Vietnamese and English.
class AppLocalizations {
  final String locale; // 'vi' or 'en'

  AppLocalizations(this.locale);

  String get(String key) =>
      (_strings[locale]?[key]) ?? (_strings['vi']?[key]) ?? key;

  static const Map<String, Map<String, String>> _strings = {
    'vi': {
      // App
      'app_name': 'Quản lý Cây',
      'app_subtitle': 'EarthRanger',
      'version': 'v1.0.0',
      'landing_title': 'V-RANGER',
      'landing_open_earthranger': 'MỞ\nEARTHRANGER',
      'landing_add_tree': 'THÊM CÂY',
      'landing_user_name': 'Nguyễn Minh Đức',
      'landing_user_role': 'Trưởng Đội Tuần Tra - Đội 01',
      'landing_user_status_on_duty': 'Đang trực',
      'landing_user_date': 'Thứ Sáu, 26 Th01 2024',
      'landing_function_work': 'Quản lý Công việc',
      'landing_function_incident': 'Quản lý lâm phần',
      'landing_function_resource': 'Quản lý Tài nguyên Rừng',
      'landing_function_schedule': 'Lịch làm việc',
      'landing_function_reports': 'Thống kê báo cáo',
      'landing_function_patrol': 'Quản lý Tuần tra',
      'incident_management_title': 'Quản lý sự cố',
      'forest_compartment_title': 'Quản lý lâm phần',
      'forest_compartment_area': 'Diện tích',
      'forest_compartment_incidents': 'Sự cố',
      'forest_compartment_resolved': 'Đã xử lý',
      'forest_compartment_unresolved': 'Chưa xử lý',
      'forest_compartment_empty': 'Chưa có tiểu khu rừng.',
      'forest_compartment_loading': 'Đang tải danh sách tiểu khu...',
      'forest_compartment_error': 'Không thể tải danh sách tiểu khu rừng.',
      'forest_compartment_resolution': 'Tỷ lệ xử lý',
      'resource_sync_note': 'Dữ liệu cây quý được đồng bộ với EarthRanger Web.',
      'resource_scan_nfc': 'Quét NFC/RFID',
      'resource_identify_plant': 'Nhận diện Thực vật',
      'resource_search_hint':
          'Tìm theo Tree ID, RFID/NFC, loài, tiểu khu, tình trạng...',
      'resource_filter_species': 'Lọc theo loài',
      'resource_filter_condition': 'Lọc theo tình trạng',
      'resource_filter_all_species': 'Tất cả loài',
      'resource_filter_all_condition': 'Tất cả tình trạng',
      'resource_stats_title': 'Thống kê nhanh',
      'resource_stats_species': 'Theo loài',
      'resource_stats_condition': 'Theo tình trạng',
      'resource_alerts_title': 'Cảnh báo chăm sóc đặc biệt',
      'resource_alerts_empty': 'Hiện chưa có cây cần cảnh báo chăm sóc.',
      'resource_send_alert': 'Gửi cảnh báo',
      'resource_alert_sent': 'Đã gửi cảnh báo chăm sóc cho cây {id}.',
      'resource_alert_sent_short': 'Đã gửi',
      'resource_open_detail': 'Xem chi tiết',
      'resource_nfc_label': 'RFID/NFC',
      'resource_nfc_empty': 'Chưa gắn RFID/NFC',
      'resource_condition': 'Tình trạng',
      'resource_age': 'Độ tuổi',
      'resource_height': 'Chiều cao',
      'resource_canopy': 'Tán lá',
      'resource_compartment': 'Tiểu khu',
      'resource_estimated_value': 'Giá trị ước tính',
      'resource_estimated_value_unknown': 'Chưa định giá',
      'resource_location': 'Vị trí',
      'resource_species_unknown': 'Chưa rõ loài',
      'resource_condition_unknown': 'Chưa rõ tình trạng',
      'resource_special_care_badge': 'Cần chăm sóc',
      'resource_tree_empty': 'Không tìm thấy cây phù hợp với bộ lọc.',
      'resource_load_error': 'Không thể tải dữ liệu cây quý.',
      'resource_total_valuable_trees': 'Tổng số cây quý',
      'resource_rare_species_count': 'Số loài hiếm',
      'resource_total_estimated_value': 'Tổng giá trị ước tính',
      'resource_health_monitoring': 'Đang theo dõi sức khỏe',
      'resource_stat_missing': 'Chưa có',
      'resource_currency_billion': 'tỷ',
      'resource_currency_million': 'triệu',
      'resource_schema_warning_title': 'Cần cập nhật cấu trúc bảng trees',
      'resource_schema_warning_check_failed':
          'Không thể kiểm tra cột thống kê tự động. Vui lòng kiểm tra thủ công bảng trees.',
      'resource_schema_warning_missing': 'Thiếu cột',
      'resource_schema_warning_sql': 'SQL gợi ý để bổ sung cột:',
      'resource_overview_title': 'Thông tin tổng quan cây',
      'resource_overview_empty':
          'Chưa có cây nào được chọn. Hãy quét RFID/NFC hoặc nhập mã cây.',
      'resource_scan_detail_prompt':
          'Quét RFID/NFC để xem thông tin chi tiết cây',
      'resource_scan_popup_title': 'Quét RFID/NFC hoặc nhập mã cây',
      'resource_scan_input_hint': 'Nhập Tree ID hoặc RFID/NFC',
      'resource_scan_start': 'Bắt đầu quét',
      'resource_scan_stop': 'Dừng quét',
      'resource_scan_fetch': 'Tải thông tin cây',
      'resource_scan_empty': 'Vui lòng nhập mã cây hoặc RFID/NFC.',
      'resource_scan_no_match': 'Không tìm thấy cây phù hợp với mã đã nhập.',
      'resource_scan_loaded': 'Đã tải thông tin cây.',
      'resource_technical_title': 'Thông số kỹ thuật',
      'resource_map_position': 'Vị trí bản đồ',
      'resource_trunk_diameter': 'Đường kính thân',
      'resource_care_title': 'Thông tin chăm sóc',
      'resource_care_history': 'Lịch sử chăm sóc',
      'resource_care_no_history': 'Chưa có lịch sử chăm sóc.',
      'resource_care_check': 'Kiểm tra định kỳ',
      'resource_care_created': 'Tạo hồ sơ',
      'resource_current_status': 'Tình trạng hiện tại',
      'resource_special_notes': 'Ghi chú đặc biệt',
      'resource_special_notes_empty': 'Không có ghi chú đặc biệt.',
      'resource_update_status': 'Cập nhật trạng thái',
      'resource_update_status_done': 'Đã gửi yêu cầu cập nhật trạng thái.',
      'resource_quick_list_title': 'Danh sách chọn nhanh',
      'resource_select_tree_prompt':
          'Chọn một cây từ danh sách bên dưới hoặc quét RFID/NFC để xem chi tiết.',

      // Reports
      'report_forest_protection': 'Bảo vệ rừng',
      'report_incidents': 'Sự cố',
      'report_work_performance': 'Hiệu suất công việc',
      'report_this_month': 'Tháng này',
      'report_this_quarter': 'Quý này',
      'report_this_year': 'Năm này',
      'report_custom': 'Tùy chọn',
      'report_loading': 'Đang tải báo cáo...',
      'report_error': 'Không tải được báo cáo.',
      'report_total_incidents': 'Tổng sự cố',
      'report_resolved': 'Đã xử lý',
      'report_unresolved': 'Chưa xử lý',
      'report_resolution_rate': 'Tỷ lệ xử lý',
      'report_by_severity': 'Theo mức độ',
      'report_by_status': 'Theo trạng thái',
      'report_by_ranger': 'Theo kiểm lâm',
      'report_checkin_rate': 'Tỷ lệ điểm danh',
      'report_total_days': 'Tổng ngày',
      'report_checkin_days': 'Ngày điểm danh',
      'report_total_rangers': 'Tổng kiểm lâm',
      'report_total_work_days': 'Tổng ngày làm việc',
      'report_total_checkin_days': 'Tổng ngày điểm danh',
      'report_overall_checkin_rate': 'Tỷ lệ điểm danh chung',
      'report_incidents_found': 'Sự cố phát hiện',

      // Home
      'home': 'Trang chủ',
      'nfc_hint': 'Nhập mã NFC hoặc Tree ID',
      'nfc_empty_error': 'Vui lòng nhập mã NFC.',
      'nfc_scan_prompt': 'Vui lòng để điện thoại gần thẻ NFC',
      'nfc_unavailable_error': 'NFC lỗi: không khả dụng hoặc đang tắt.',
      'nfc_uid_read_error': 'Không thể đọc mã UID từ thẻ NFC.',
      'nfc_ios_unavailable_temp': 'Chức năng NFC tạm thời không có trên iOS.',
      'search': 'Tìm kiếm',
      'search_failed':
          'Tìm kiếm thất bại. Vui lòng kiểm tra kết nối và thử lại.',
      'link_tree_action': 'Liên kết cây',
      'id_label': 'ID',
      'not_available': 'N/A',
      'maps': 'Bản đồ',
      'alerts': 'Cảnh báo',
      'alerts_empty': 'Không có cảnh báo',
      'alerts_loading': 'Đang tải cảnh báo...',
      'alerts_error': 'Không thể tải cảnh báo.',
      'alerts_severity_prefix': 'Mức độ: ',
      'alerts_status_prefix': 'Trạng thái: ',
      'alerts_time_prefix': 'Thời gian: ',
      'notifications': 'Thông báo',
      'account': 'Tài khoản',
      'placeholder_coming_soon': 'Màn hình chức năng đang được phát triển.',
      'work_checkin_title': 'Điểm danh khi mở ứng dụng',
      'work_checkin_syncing': 'Đang đồng bộ điểm danh...',
      'work_checkin_status_created': 'Đã ghi nhận điểm danh hôm nay',
      'work_checkin_status_exists': 'Hôm nay đã điểm danh trước đó',
      'work_checkin_status_pending': 'Đã lưu tạm, chờ đồng bộ khi có mạng',
      'work_checkin_status_unknown': 'Chưa có trạng thái điểm danh',
      'work_checkin_day_pending': 'Ngày điểm danh: chưa có dữ liệu',
      'work_checkin_day_prefix': 'Ngày điểm danh: ',
      'work_checkin_error_prefix': 'Lỗi điểm danh: ',
      'work_sync_status_title': 'Trạng thái đồng bộ',
      'work_sync_status_empty': 'Chưa có bản ghi đồng bộ cục bộ.',
      'work_sync_status_pending': 'Đang chờ',
      'work_sync_status_synced': 'Đã đồng bộ',
      'work_sync_status_failed': 'Thất bại',
      'work_sync_status_count_pending': 'Chờ',
      'work_sync_status_count_failed': 'Lỗi',
      'work_sync_status_count_synced': 'Đồng bộ',
      'work_sync_status_updated_prefix': 'Cập nhật: ',
      'work_sync_status_retry_at_prefix': 'Thử lại lúc: ',
      'work_sync_status_error_prefix': 'Lỗi: ',
      'work_sync_status_retry_item': 'Thử lại mục này',
      'work_sync_status_retry_all': 'Thử lại tất cả mục lỗi',
      'work_sync_status_retrying': 'Đang thử lại mục lỗi...',
      'work_calendar_role_label': 'Vai trò',
      'work_calendar_role_leader': 'Trưởng nhóm',
      'work_calendar_role_ranger': 'Kiểm lâm',
      'work_calendar_scope_team': 'Phạm vi: toàn đội',
      'work_calendar_scope_self': 'Phạm vi: cá nhân',
      'work_calendar_filter_label': 'Lọc kiểm lâm',
      'work_calendar_filter_all': 'Tất cả kiểm lâm',
      'work_calendar_loading': 'Đang tải dữ liệu lịch công việc...',
      'work_calendar_empty':
          'Không có dữ liệu lịch cho phạm vi và tháng đã chọn.',
      'work_calendar_error': 'Không thể tải dữ liệu lịch công việc.',
      'work_calendar_retry': 'Tải lại',
      'work_calendar_last_sync_prefix': 'Đồng bộ gần nhất: ',
      'work_calendar_last_sync_unknown': 'chưa có dữ liệu',
      'work_calendar_stale_banner':
          'Dữ liệu lịch công việc có thể đã cũ. Vui lòng làm mới khi có mạng.',
      'work_calendar_offline_banner':
          'Đang hiển thị dữ liệu đã lưu do kết nối mạng không ổn định.',
      'work_calendar_refresh_error_prefix': 'Lỗi làm mới: ',
      'work_calendar_day_no_data': 'Ngày đã chọn chưa có dữ liệu công việc.',
      'work_calendar_day_all_checked':
          'Ngày đã chọn: tất cả bản ghi đã điểm danh.',
      'work_calendar_day_none_checked':
          'Ngày đã chọn: chưa có bản ghi điểm danh.',
      'work_calendar_day_partial_prefix': 'Ngày đã chọn: ',
      'work_calendar_day_partial_suffix': ' bản ghi đã điểm danh (một phần).',
      'work_stats_title': 'Thống kê nhân viên tháng này',
      'work_stats_checkin_rate': 'Tỷ lệ điểm danh',
      'work_stats_incidents': 'Sự cố phát hiện',

      'incident_scope_label': 'Phạm vi sự cố',
      'incident_role_leader': 'Trưởng nhóm',
      'incident_role_ranger': 'Kiểm lâm',
      'incident_scope_team': 'Hiển thị toàn đội',
      'incident_scope_self': 'Hiển thị cá nhân',
      'incident_last_sync_prefix': 'Đồng bộ gần nhất: ',
      'incident_last_sync_unknown': 'chưa có dữ liệu',
      'incident_loading': 'Đang tải danh sách sự cố...',
      'incident_empty': 'Không có sự cố nào trong khoảng thời gian đã chọn.',
      'incident_error': 'Không thể tải danh sách sự cố.',
      'incident_retry': 'Thử tải lại',
      'incident_stale_banner':
          'Dữ liệu có thể đã cũ. Vui lòng kéo xuống hoặc nhấn làm mới.',
      'incident_offline_banner':
          'Đang hiển thị dữ liệu đã lưu do thiết bị đang offline hoặc mạng lỗi.',
      'incident_cached_banner':
          'Đang hiển thị dữ liệu cache trong khi làm mới nền.',
      'incident_leakage_filtered_banner':
          'Đã lọc dữ liệu sự cố ngoài phạm vi hiển thị của bạn để bảo toàn quyền truy cập.',
      'incident_refresh_error_prefix': 'Lỗi làm mới: ',
      'incident_refresh_retry_hint': 'Nhấn làm mới để thử lại.',
      'incident_error_timeout': 'Hết thời gian chờ khi tải dữ liệu sự cố.',
      'incident_error_network': 'Mạng không khả dụng.',
      'incident_error_unexpected': 'Đã xảy ra lỗi không mong muốn.',
      'incident_unknown_title': 'Sự cố chưa có tiêu đề',
      'incident_unknown_time': 'Không rõ thời gian',
      'incident_empty_stale':
          'Không có sự cố trong bản dữ liệu cũ. Vui lòng làm mới khi có mạng.',
      'incident_unknown_severity': 'Không rõ mức độ',
      'incident_unknown_status': 'Không rõ trạng thái',
      'incident_status_prefix': 'Trạng thái: ',
      'incident_time_prefix': 'Thời điểm: ',
      'incident_ranger_prefix': 'Kiểm lâm: ',
      'schedule_scope_label': 'Phạm vi lịch',
      'schedule_role_leader': 'Trưởng nhóm',
      'schedule_role_ranger': 'Kiểm lâm',
      'schedule_scope_team': 'Hiển thị toàn đội',
      'schedule_scope_self': 'Hiển thị cá nhân',
      'schedule_filter_label': 'Lọc kiểm lâm',
      'schedule_filter_all': 'Tất cả kiểm lâm',
      'schedule_filter_all_staff': 'Tất cả trưởng nhóm/kiểm lâm',
      'schedule_loading': 'Đang tải lịch làm việc...',
      'schedule_empty': 'Không có lịch làm việc trong tháng đã chọn.',
      'schedule_error': 'Không thể tải lịch làm việc.',
      'schedule_retry': 'Thử tải lại',
      'schedule_last_sync_prefix': 'Đồng bộ gần nhất: ',
      'schedule_last_sync_unknown': 'chưa có dữ liệu',
      'schedule_stale_banner':
          'Dữ liệu lịch có thể đã cũ. Vui lòng làm mới khi có mạng.',
      'schedule_offline_banner':
          'Đang hiển thị dữ liệu đã lưu do kết nối mạng không ổn định.',
      'schedule_refresh_error_prefix': 'Lỗi làm mới: ',
      'schedule_create': 'Tạo lịch',
      'schedule_edit': 'Chỉnh sửa lịch',
      'schedule_delete': 'Xoá lịch',
      'schedule_delete_confirm_title': 'Xoá lịch làm việc',
      'schedule_delete_confirm_message':
          'Bạn có chắc muốn xoá lịch làm việc này không?',
      'schedule_delete_confirm_action': 'Xoá',
      'schedule_delete_success': 'Đã xoá lịch làm việc.',
      'schedule_delete_error': 'Không thể xoá lịch làm việc.',
      'schedule_delete_error_prefix': 'Lỗi xoá lịch: ',
      'schedule_form_title_create': 'Tạo lịch làm việc',
      'schedule_form_title_edit': 'Cập nhật lịch làm việc',
      'schedule_form_ranger_label': 'Người được phân công',
      'schedule_form_date_label': 'Ngày làm việc',
      'schedule_form_note_label': 'Ghi chú',
      'schedule_form_note_hint': 'Nhập ghi chú phân công (tuỳ chọn)',
      'schedule_form_save': 'Lưu',
      'schedule_form_saving': 'Đang lưu...',
      'schedule_form_cancel': 'Huỷ',
      'schedule_validation_ranger_required':
          'Vui lòng chọn người được phân công.',
      'schedule_validation_work_date_required': 'Vui lòng chọn ngày làm việc.',
      'schedule_submit_error_prefix': 'Lỗi lưu lịch: ',
      'schedule_date_prefix': 'Ngày: ',
      'schedule_ranger_prefix': 'Kiểm lâm: ',
      'schedule_note_empty': 'Không có ghi chú.',
      'schedule_updated_by_prefix': 'Cập nhật bởi: ',
      'schedule_updated_at_prefix': 'Cập nhật lúc: ',
      'schedule_updated_by_unknown': 'không rõ',
      'schedule_updated_at_unknown': 'không rõ',

      // Admin login dialog
      'login_status_logged_in': 'Trạng thái: Đã đăng nhập Admin',
      'login_status_logged_out': 'Trạng thái: Chưa đăng nhập',
      'sign_in_title': 'Đăng nhập',
      'sign_in_subtitle': 'Dùng tài khoản EarthRanger để tiếp tục',
      'sign_in_action': 'Đăng nhập',
      'remember_me': 'Ghi nhớ đăng nhập',
      'restoring_session': 'Đang khôi phục phiên đăng nhập...',
      'login': 'Đăng nhập',
      'logout': 'Đăng xuất',
      'cancel': 'Hủy',
      'username_hint': 'Tên đăng nhập',
      'password_hint': 'Mật khẩu',
      'username_empty_error': 'Vui lòng nhập tên đăng nhập.',
      'password_empty_error': 'Vui lòng nhập mật khẩu.',
      'login_success': 'Đăng nhập Admin thành công!',
      'login_failed': 'Sai tên đăng nhập hoặc mật khẩu!',
      'login_empty_error': 'Vui lòng nhập tên đăng nhập và mật khẩu.',
      'invalid_credentials': 'Tên đăng nhập hoặc mật khẩu không đúng.',
      'network_error_try_again': 'Không thể kết nối. Vui lòng thử lại.',
      'session_expired_relogin': 'Phiên đã hết hạn. Vui lòng đăng nhập lại.',
      'show_password': 'Hiện mật khẩu',
      'hide_password': 'Ẩn mật khẩu',
      'login_not_configured': 'Đăng nhập Admin chưa được cấu hình.',
      'logged_out': 'Đã đăng xuất khỏi Admin',
      'signed_out': 'Bạn đã đăng xuất.',
      'admin_login': 'Đăng nhập Admin',

      // Tree detail
      'tree_info': 'Thông tin Cây',
      'species': 'Loài',
      'age': 'Tuổi',
      'height': 'Chiều cao',
      'diameter': 'Đường kính',
      'canopy': 'Tán lá',
      'condition': 'Tình trạng',
      'latitude': 'Vĩ độ',
      'longitude': 'Kinh độ',
      'created_at': 'Ngày tạo',
      'creator': 'Người tạo',
      'last_reported': 'Cập nhật cuối',
      'updater': 'Người cập nhật',
      'event_status': 'Trạng thái sự kiện',
      'sn': 'SN',
      'synced_at': 'Đồng bộ lúc',
      'nfc_id': 'NFC ID',
      'not_found': 'Không tìm thấy cây',
      'not_found_detail': 'Không tìm thấy dữ liệu cho mã NFC này.',
      'go_back': 'Quay lại',
      'no_images': 'Không có hình ảnh',
      'no_nfc': 'Không có mã NFC được cung cấp.',
      'fetch_failed': 'Lấy dữ liệu cây thất bại.',
      'no_edit_permission': 'Bạn không có quyền chỉnh sửa.',
      'no_data_to_edit': 'Không có dữ liệu để chỉnh sửa.',

      // Edit dialog
      'edit_tree': 'Chỉnh sửa thông tin cây',
      'tree_id_label': 'Tree ID',
      'tree_id_required': 'Vui lòng nhập Tree ID',
      'save': 'Lưu',
      'update_success': 'Cập nhật thông tin thành công!',
      'update_failed': 'Cập nhật thất bại',
      'condition_good': 'Tốt',
      'condition_average': 'Trung bình',
      'condition_bad': 'Xấu',

      // Section headers
      'stats': 'Thông số',
      'history': 'Lịch sử',
      'technical': 'Thông tin kỹ thuật',

      // Settings
      'settings': 'Cài đặt',
      'language': 'Ngôn ngữ',
      'vietnamese': 'Tiếng Việt',
      'english': 'English',
      'theme': 'Giao diện',
      'light_mode': 'Sáng',
      'dark_mode': 'Tối',
      'system_mode': 'Theo hệ thống',
      'appearance': 'Hiển thị',
      'general': 'Chung',

      // Sign-up
      'signup_title': 'Đăng ký tài khoản',
      'signup_subtitle': 'Tạo tài khoản mới để sử dụng V-Ranger',
      'signup_username_hint': 'Tên đăng nhập',
      'signup_username_empty_error': 'Vui lòng nhập tên đăng nhập.',
      'signup_username_min_error': 'Tên đăng nhập phải có ít nhất 3 ký tự.',
      'signup_password_hint': 'Mật khẩu',
      'signup_password_empty_error': 'Vui lòng nhập mật khẩu.',
      'signup_password_min_error': 'Mật khẩu phải có ít nhất 6 ký tự.',
      'signup_confirm_password_hint': 'Nhập lại mật khẩu',
      'signup_confirm_password_empty_error': 'Vui lòng nhập lại mật khẩu.',
      'signup_password_mismatch_error': 'Mật khẩu không khớp.',
      'signup_display_name_hint': 'Họ và tên',
      'signup_display_name_empty_error': 'Vui lòng nhập họ và tên.',
      'signup_region_hint': 'Khu vực (tuỳ chọn)',
      'signup_phone_hint': 'Số điện thoại (tuỳ chọn)',
      'signup_submit': 'Đăng ký',
      'signup_success_title': 'Đăng ký thành công!',
      'signup_success_pending':
          'Tài khoản của bạn đang chờ quản trị viên phê duyệt. Vui lòng liên hệ quản trị viên để kích hoạt tài khoản.',
      'signup_back_to_login': 'Quay lại đăng nhập',
      'signup_registration_failed': 'Đăng ký thất bại. Vui lòng thử lại.',
      'signup_already_have_account': 'Đã có tài khoản? ',
      'signup_sign_in': 'Đăng nhập',
      'login_no_account': 'Chưa có tài khoản? ',
      'login_create_account': 'Đăng ký',
      'login_account_pending': 'Tài khoản đang chờ phê duyệt.',
      'login_account_rejected': 'Tài khoản đã bị từ chối.',

      // Account
      'account_display_name': 'Họ và tên',
      'account_username': 'Tên đăng nhập',
      'account_role': 'Vai trò',
      'account_region': 'Khu vực',
      'account_phone': 'Số điện thoại',
      'account_change_photo': 'Thay đổi ảnh đại diện',
      'account_pick_gallery': 'Chọn từ thư viện',
      'account_pick_camera': 'Chụp ảnh mới',
      'account_profile_load_error': 'Không thể tải thông tin tài khoản.',
      'account_profile_save_error': 'Không thể lưu thông tin tài khoản.',
      'account_avatar_upload_error': 'Không thể tải ảnh đại diện lên.',
      'account_need_mobile_session':
          'Vui lòng đăng nhập để xem thông tin tài khoản.',

      // Carousel
      'carousel_add_media': 'Nhấn để thêm ảnh',
      'carousel_change_media': 'Thay đổi ảnh',

      // Link tree
      'link_nfc': 'Liên kết NFC',
      'link_nfc_title': 'Chọn cây để liên kết',
      'search_tree_hint': 'Tìm kiếm theo ID hoặc loài',
      'unlinked_trees': 'Cây chưa liên kết',
      'linked_trees': 'Cây đã liên kết',
      'has_nfc': 'Đã có NFC',
      'no_nfc_tag': 'Chưa có NFC',
      'replace_nfc_title': 'Thay thế NFC',
      'replace_nfc_message':
          'Cây {id} đã có NFC: {nfc}. Bạn có muốn thay thế không?',
      'confirm': 'Xác nhận',
      'link_success': 'Liên kết NFC thành công!',
      'link_failed': 'Liên kết thất bại',
      'no_trees_found': 'Không tìm thấy cây nào',
      'retry': 'Thử lại',
    },
    'en': {
      // App
      'app_name': 'Tree Manager',
      'app_subtitle': 'EarthRanger',
      'version': 'v1.0.0',
      'landing_title': 'V-RANGER',
      'landing_open_earthranger': 'OPEN\nEARTHRANGER',
      'landing_add_tree': 'ADD TREE',
      'landing_user_name': 'Nguyen Minh Duc',
      'landing_user_role': 'Patrol Team Leader - Team 01',
      'landing_user_status_on_duty': 'On Duty',
      'landing_user_date': 'Friday, Jan 26 2024',
      'landing_function_work': 'Work Management',
      'landing_function_incident': 'Compartment Management',
      'landing_function_resource': 'Forest Resource Management',
      'landing_function_schedule': 'Work Schedule',
      'landing_function_reports': 'Report Statistics',
      'landing_function_patrol': 'Patrol Management',
      'incident_management_title': 'Incident Management',
      'forest_compartment_title': 'Compartment Management',
      'forest_compartment_area': 'Area',
      'forest_compartment_incidents': 'Incidents',
      'forest_compartment_resolved': 'Resolved',
      'forest_compartment_unresolved': 'Unresolved',
      'forest_compartment_empty': 'No forest compartments yet.',
      'forest_compartment_loading': 'Loading compartments...',
      'forest_compartment_error': 'Could not load forest compartments.',
      'forest_compartment_resolution': 'Resolution rate',
      'resource_sync_note':
          'Valuable-tree data is synchronized with EarthRanger Web.',
      'resource_scan_nfc': 'Scan NFC/RFID',
      'resource_identify_plant': 'Plant Identification',
      'resource_search_hint':
          'Search by Tree ID, RFID/NFC, species, compartment, condition...',
      'resource_filter_species': 'Filter by species',
      'resource_filter_condition': 'Filter by condition',
      'resource_filter_all_species': 'All species',
      'resource_filter_all_condition': 'All conditions',
      'resource_stats_title': 'Quick statistics',
      'resource_stats_species': 'By species',
      'resource_stats_condition': 'By condition',
      'resource_alerts_title': 'Special-care alerts',
      'resource_alerts_empty':
          'No trees currently require special care alerts.',
      'resource_send_alert': 'Send alert',
      'resource_alert_sent': 'Special-care alert sent for tree {id}.',
      'resource_alert_sent_short': 'Sent',
      'resource_open_detail': 'View details',
      'resource_nfc_label': 'RFID/NFC',
      'resource_nfc_empty': 'No RFID/NFC linked',
      'resource_condition': 'Condition',
      'resource_age': 'Age',
      'resource_height': 'Height',
      'resource_canopy': 'Canopy',
      'resource_compartment': 'Compartment',
      'resource_estimated_value': 'Estimated value',
      'resource_estimated_value_unknown': 'Not estimated yet',
      'resource_location': 'Location',
      'resource_species_unknown': 'Unknown species',
      'resource_condition_unknown': 'Unknown condition',
      'resource_special_care_badge': 'Needs care',
      'resource_tree_empty': 'No trees match the selected filters.',
      'resource_load_error': 'Could not load valuable-tree data.',
      'resource_total_valuable_trees': 'Total valuable trees',
      'resource_rare_species_count': 'Rare species count',
      'resource_total_estimated_value': 'Total estimated value',
      'resource_health_monitoring': 'Health monitoring',
      'resource_stat_missing': 'N/A',
      'resource_currency_billion': 'billion',
      'resource_currency_million': 'million',
      'resource_schema_warning_title': 'Tree table schema update required',
      'resource_schema_warning_check_failed':
          'Automatic metric-column check failed. Please verify the trees table manually.',
      'resource_schema_warning_missing': 'Missing columns',
      'resource_schema_warning_sql': 'Suggested SQL to add columns:',
      'resource_overview_title': 'Tree overview',
      'resource_overview_empty':
          'No tree selected. Scan RFID/NFC or enter a tree code.',
      'resource_scan_detail_prompt':
          'Scan RFID/NFC to view detailed tree information',
      'resource_scan_popup_title': 'Scan RFID/NFC or enter tree code',
      'resource_scan_input_hint': 'Enter Tree ID or RFID/NFC',
      'resource_scan_start': 'Start scan',
      'resource_scan_stop': 'Stop scan',
      'resource_scan_fetch': 'Fetch tree',
      'resource_scan_empty': 'Please enter a tree code or RFID/NFC.',
      'resource_scan_no_match': 'No matching tree found for the entered code.',
      'resource_scan_loaded': 'Tree information loaded.',
      'resource_technical_title': 'Technical information',
      'resource_map_position': 'Map position',
      'resource_trunk_diameter': 'Trunk diameter',
      'resource_care_title': 'Care information',
      'resource_care_history': 'Care history',
      'resource_care_no_history': 'No care history available yet.',
      'resource_care_check': 'Routine check',
      'resource_care_created': 'Record created',
      'resource_current_status': 'Current status',
      'resource_special_notes': 'Special notes',
      'resource_special_notes_empty': 'No special notes.',
      'resource_update_status': 'Update status',
      'resource_update_status_done': 'Status update request sent.',
      'resource_quick_list_title': 'Quick select list',
      'resource_select_tree_prompt':
          'Select a tree from the list below or scan RFID/NFC to view details.',

      // Reports
      'report_forest_protection': 'Forest Protection',
      'report_incidents': 'Incidents',
      'report_work_performance': 'Work Performance',
      'report_this_month': 'This Month',
      'report_this_quarter': 'This Quarter',
      'report_this_year': 'This Year',
      'report_custom': 'Custom',
      'report_loading': 'Loading report...',
      'report_error': 'Could not load report.',
      'report_total_incidents': 'Total incidents',
      'report_resolved': 'Resolved',
      'report_unresolved': 'Unresolved',
      'report_resolution_rate': 'Resolution rate',
      'report_by_severity': 'By severity',
      'report_by_status': 'By status',
      'report_by_ranger': 'By ranger',
      'report_checkin_rate': 'Check-in rate',
      'report_total_days': 'Total days',
      'report_checkin_days': 'Check-in days',
      'report_total_rangers': 'Total rangers',
      'report_total_work_days': 'Total work days',
      'report_total_checkin_days': 'Total check-in days',
      'report_overall_checkin_rate': 'Overall check-in rate',
      'report_incidents_found': 'Incidents found',

      // Home
      'home': 'Home',
      'nfc_hint': 'Enter NFC code or Tree ID',
      'nfc_empty_error': 'Please enter an NFC code.',
      'nfc_scan_prompt': 'Please hold your phone near the NFC tag',
      'nfc_unavailable_error': 'NFC error: unavailable or disabled.',
      'nfc_uid_read_error': 'Could not read NFC UID from the tag.',
      'nfc_ios_unavailable_temp': 'NFC is temporarily unavailable on iOS.',
      'search': 'Search',
      'search_failed':
          'Search failed. Please check your connection and try again.',
      'link_tree_action': 'Link tree',
      'id_label': 'ID',
      'not_available': 'N/A',
      'maps': 'Maps',
      'alerts': 'Alerts',
      'alerts_empty': 'No alerts',
      'alerts_loading': 'Loading alerts...',
      'alerts_error': 'Could not load alerts.',
      'alerts_severity_prefix': 'Severity: ',
      'alerts_status_prefix': 'Status: ',
      'alerts_time_prefix': 'Time: ',
      'notifications': 'Notifications',
      'account': 'Account',
      'placeholder_coming_soon': 'This feature screen is coming soon.',
      'work_checkin_title': 'App-open check-in',
      'work_checkin_syncing': 'Syncing check-in...',
      'work_checkin_status_created': 'Check-in recorded for today',
      'work_checkin_status_exists': 'Check-in already exists for today',
      'work_checkin_status_pending': 'Queued offline, waiting for replay',
      'work_checkin_status_unknown': 'No check-in status yet',
      'work_checkin_day_pending': 'Check-in day: no data yet',
      'work_checkin_day_prefix': 'Check-in day: ',
      'work_checkin_error_prefix': 'Check-in error: ',
      'work_sync_status_title': 'Sync status',
      'work_sync_status_empty': 'No local sync records yet.',
      'work_sync_status_pending': 'Pending',
      'work_sync_status_synced': 'Synced',
      'work_sync_status_failed': 'Failed',
      'work_sync_status_count_pending': 'Pending',
      'work_sync_status_count_failed': 'Failed',
      'work_sync_status_count_synced': 'Synced',
      'work_sync_status_updated_prefix': 'Updated: ',
      'work_sync_status_retry_at_prefix': 'Retry at: ',
      'work_sync_status_error_prefix': 'Error: ',
      'work_sync_status_retry_item': 'Retry this item',
      'work_sync_status_retry_all': 'Retry all failed items',
      'work_sync_status_retrying': 'Retrying failed items...',
      'work_calendar_role_label': 'Role',
      'work_calendar_role_leader': 'Leader',
      'work_calendar_role_ranger': 'Ranger',
      'work_calendar_scope_team': 'Scope: team view',
      'work_calendar_scope_self': 'Scope: self view',
      'work_calendar_filter_label': 'Ranger filter',
      'work_calendar_filter_all': 'All rangers',
      'work_calendar_loading': 'Loading work calendar data...',
      'work_calendar_empty':
          'No calendar data for the selected scope and month.',
      'work_calendar_error': 'Unable to load Work Management data.',
      'work_calendar_retry': 'Retry',
      'work_calendar_last_sync_prefix': 'Last sync: ',
      'work_calendar_last_sync_unknown': 'no sync data',
      'work_calendar_stale_banner':
          'Work calendar data may be stale. Refresh when network is available.',
      'work_calendar_offline_banner':
          'Showing cached data because the network is currently unavailable.',
      'work_calendar_refresh_error_prefix': 'Refresh error: ',
      'work_calendar_day_no_data': 'No work data for the selected day.',
      'work_calendar_day_all_checked':
          'Selected day: all records have confirmed check-in.',
      'work_calendar_day_none_checked':
          'Selected day: no records have check-in yet.',
      'work_calendar_day_partial_prefix': 'Selected day: ',
      'work_calendar_day_partial_suffix':
          ' records have check-in (partial coverage).',
      'work_stats_title': 'Employee stats this month',
      'work_stats_checkin_rate': 'Check-in rate',
      'work_stats_incidents': 'Incidents found',

      'incident_scope_label': 'Incident scope',
      'incident_role_leader': 'Leader',
      'incident_role_ranger': 'Ranger',
      'incident_scope_team': 'Team-wide view',
      'incident_scope_self': 'Self-only view',
      'incident_last_sync_prefix': 'Last sync: ',
      'incident_last_sync_unknown': 'no sync data',
      'incident_loading': 'Loading incidents...',
      'incident_empty': 'No incidents found for the selected period.',
      'incident_error': 'Unable to load incidents.',
      'incident_retry': 'Retry',
      'incident_stale_banner':
          'Data may be stale. Pull to refresh or tap refresh.',
      'incident_offline_banner':
          'Showing cached data because the device is offline or network refresh failed.',
      'incident_cached_banner':
          'Showing cached data while a background refresh is in progress.',
      'incident_leakage_filtered_banner':
          'Out-of-scope incident records were filtered to preserve access boundaries.',
      'incident_refresh_error_prefix': 'Refresh error: ',
      'incident_refresh_retry_hint': 'Tap refresh to retry.',
      'incident_error_timeout': 'Request timed out while loading incidents.',
      'incident_error_network': 'Network unavailable.',
      'incident_error_unexpected': 'An unexpected error occurred.',
      'incident_unknown_title': 'Untitled incident',
      'incident_unknown_time': 'Unknown time',
      'incident_empty_stale':
          'No incidents found in stale data. Refresh when network is available.',
      'incident_unknown_severity': 'Unknown severity',
      'incident_unknown_status': 'Unknown status',
      'incident_status_prefix': 'Status: ',
      'incident_time_prefix': 'Time: ',
      'incident_ranger_prefix': 'Ranger: ',
      'schedule_scope_label': 'Schedule scope',
      'schedule_role_leader': 'Leader',
      'schedule_role_ranger': 'Ranger',
      'schedule_scope_team': 'Team-wide view',
      'schedule_scope_self': 'Self-only view',
      'schedule_filter_label': 'Ranger filter',
      'schedule_filter_all': 'All rangers',
      'schedule_filter_all_staff': 'All leaders/rangers',
      'schedule_loading': 'Loading schedules...',
      'schedule_empty': 'No schedules found for the selected month.',
      'schedule_error': 'Unable to load schedules.',
      'schedule_retry': 'Retry',
      'schedule_last_sync_prefix': 'Last sync: ',
      'schedule_last_sync_unknown': 'no sync data',
      'schedule_stale_banner':
          'Schedule data may be stale. Refresh when network is available.',
      'schedule_offline_banner':
          'Showing cached data because the network is currently unavailable.',
      'schedule_refresh_error_prefix': 'Refresh error: ',
      'schedule_create': 'Create schedule',
      'schedule_edit': 'Edit schedule',
      'schedule_delete': 'Delete schedule',
      'schedule_delete_confirm_title': 'Delete schedule',
      'schedule_delete_confirm_message':
          'Are you sure you want to delete this work schedule?',
      'schedule_delete_confirm_action': 'Delete',
      'schedule_delete_success': 'Schedule deleted.',
      'schedule_delete_error': 'Unable to delete schedule.',
      'schedule_delete_error_prefix': 'Schedule delete error: ',
      'schedule_form_title_create': 'Create schedule',
      'schedule_form_title_edit': 'Update schedule',
      'schedule_form_ranger_label': 'Assignee',
      'schedule_form_date_label': 'Work date',
      'schedule_form_note_label': 'Note',
      'schedule_form_note_hint': 'Enter assignment note (optional)',
      'schedule_form_save': 'Save',
      'schedule_form_saving': 'Saving...',
      'schedule_form_cancel': 'Cancel',
      'schedule_validation_ranger_required': 'Please select an assignee.',
      'schedule_validation_work_date_required': 'Please select a work date.',
      'schedule_submit_error_prefix': 'Schedule save error: ',
      'schedule_date_prefix': 'Date: ',
      'schedule_ranger_prefix': 'Ranger: ',
      'schedule_note_empty': 'No note provided.',
      'schedule_updated_by_prefix': 'Updated by: ',
      'schedule_updated_at_prefix': 'Updated at: ',
      'schedule_updated_by_unknown': 'unknown',
      'schedule_updated_at_unknown': 'unknown',

      // Admin login dialog
      'login_status_logged_in': 'Status: Admin logged in',
      'login_status_logged_out': 'Status: Not logged in',
      'sign_in_title': 'Sign in',
      'sign_in_subtitle': 'Use your EarthRanger account to continue',
      'sign_in_action': 'Sign in',
      'remember_me': 'Remember me',
      'restoring_session': 'Restoring your session...',
      'login': 'Login',
      'logout': 'Logout',
      'cancel': 'Cancel',
      'username_hint': 'Username',
      'password_hint': 'Password',
      'username_empty_error': 'Please enter username.',
      'password_empty_error': 'Please enter password.',
      'login_success': 'Admin login successful!',
      'login_failed': 'Wrong username or password!',
      'login_empty_error': 'Please enter username and password.',
      'invalid_credentials': 'Username or password is incorrect.',
      'network_error_try_again': 'Cannot connect. Please try again.',
      'session_expired_relogin': 'Session expired. Please sign in again.',
      'show_password': 'Show password',
      'hide_password': 'Hide password',
      'login_not_configured': 'Admin login is not configured.',
      'logged_out': 'Logged out from Admin',
      'signed_out': 'You have been signed out.',
      'admin_login': 'Admin Login',

      // Tree detail
      'tree_info': 'Tree Info',
      'species': 'Species',
      'age': 'Age',
      'height': 'Height',
      'diameter': 'Diameter',
      'canopy': 'Canopy',
      'condition': 'Condition',
      'latitude': 'Latitude',
      'longitude': 'Longitude',
      'created_at': 'Created',
      'creator': 'Creator',
      'last_reported': 'Last reported',
      'updater': 'Updater',
      'event_status': 'Event status',
      'sn': 'SN',
      'synced_at': 'Synced at',
      'nfc_id': 'NFC ID',
      'not_found': 'Tree not found',
      'not_found_detail': 'No data found for this NFC code.',
      'go_back': 'Go back',
      'no_images': 'No images',
      'no_nfc': 'No NFC code provided.',
      'fetch_failed': 'Failed to fetch tree data.',
      'no_edit_permission': 'You do not have edit permission.',
      'no_data_to_edit': 'No data to edit.',

      // Edit dialog
      'edit_tree': 'Edit tree info',
      'tree_id_label': 'Tree ID',
      'tree_id_required': 'Please enter Tree ID',
      'save': 'Save',
      'update_success': 'Update successful!',
      'update_failed': 'Update failed',
      'condition_good': 'Good',
      'condition_average': 'Average',
      'condition_bad': 'Bad',

      // Section headers
      'stats': 'Statistics',
      'history': 'History',
      'technical': 'Technical Info',

      // Settings
      'settings': 'Settings',
      'language': 'Language',
      'vietnamese': 'Tiếng Việt',
      'english': 'English',
      'theme': 'Theme',
      'light_mode': 'Light',
      'dark_mode': 'Dark',
      'system_mode': 'System',
      'appearance': 'Appearance',
      'general': 'General',

      // Sign-up
      'signup_title': 'Create Account',
      'signup_subtitle': 'Register a new V-Ranger account',
      'signup_username_hint': 'Username',
      'signup_username_empty_error': 'Please enter a username.',
      'signup_username_min_error': 'Username must be at least 3 characters.',
      'signup_password_hint': 'Password',
      'signup_password_empty_error': 'Please enter a password.',
      'signup_password_min_error': 'Password must be at least 6 characters.',
      'signup_confirm_password_hint': 'Confirm password',
      'signup_confirm_password_empty_error': 'Please confirm your password.',
      'signup_password_mismatch_error': 'Passwords do not match.',
      'signup_display_name_hint': 'Full name',
      'signup_display_name_empty_error': 'Please enter your full name.',
      'signup_region_hint': 'Region (optional)',
      'signup_phone_hint': 'Phone number (optional)',
      'signup_submit': 'Register',
      'signup_success_title': 'Registration Successful!',
      'signup_success_pending':
          'Your account is pending admin approval. Please contact your administrator to activate your account.',
      'signup_back_to_login': 'Back to Login',
      'signup_registration_failed': 'Registration failed. Please try again.',
      'signup_already_have_account': 'Already have an account? ',
      'signup_sign_in': 'Sign in',
      'login_no_account': 'Don\'t have an account? ',
      'login_create_account': 'Register',
      'login_account_pending': 'Account is pending approval.',
      'login_account_rejected': 'Account has been rejected.',

      // Account
      'account_display_name': 'Full Name',
      'account_username': 'Username',
      'account_role': 'Role',
      'account_region': 'Region',
      'account_phone': 'Phone',
      'account_change_photo': 'Change Photo',
      'account_pick_gallery': 'Choose from gallery',
      'account_pick_camera': 'Take a photo',
      'account_profile_load_error': 'Unable to load profile.',
      'account_profile_save_error': 'Unable to save profile.',
      'account_avatar_upload_error': 'Unable to upload avatar.',
      'account_need_mobile_session': 'Please sign in to view account details.',

      // Carousel
      'carousel_add_media': 'Tap to add media',
      'carousel_change_media': 'Change media',

      // Link tree
      'link_nfc': 'Link NFC',
      'link_nfc_title': 'Select tree to link',
      'search_tree_hint': 'Search by ID or species',
      'unlinked_trees': 'Unlinked trees',
      'linked_trees': 'Linked trees',
      'has_nfc': 'Has NFC',
      'no_nfc_tag': 'No NFC',
      'replace_nfc_title': 'Replace NFC',
      'replace_nfc_message':
          'Tree {id} already has NFC: {nfc}. Do you want to replace it?',
      'confirm': 'Confirm',
      'link_success': 'NFC linked successfully!',
      'link_failed': 'Link failed',
      'no_trees_found': 'No trees found',
      'retry': 'Retry',
    },
  };
}
